### PR TITLE
Prepare release.

### PR DESCRIPTION
**Pull request by stefanbirkner**
Describe the release process and use Stefan Birkner's parent POM. This POM sets versions for all plugins and configures plugins that are used for releasing the library.

I used my own parent POM in order to avoid copying all the plugin configuration. I can create a different pull request with an explicit configuration of the plugins if you don't like to use the parent POM.

### CODE REVIEW

**Comment by stefanbirkner** [comment]
You have to add the ossrh username and password to your settings:

``` xml
<settings>
  <servers>
    <server>
      <id>ossrh</id>
      <username>your-jira-id</username>
      <password>your-jira-pwd</password>
    </server>
  </servers>
</settings>
```

**Comment by npathai** [comment]
@stefanbirkner Sorry to bother you. I have created a ticket for OSSRH access. I was learning about publishing artifacts and stumbled upon PGP signing. It might sound like a dumb question but do I need to worry about signing the artifacts?

**Comment by stefanbirkner** [comment]
AFAIK it is mandatory to sign artifacts that are published to Maven Central.

**Comment by npathai** [comment]
@stefanbirkner Thought as much. And there is a follow up question, I have understood that I need to generate public private key pair and share the public key on the server. Sign my artifacts and then upload.

The question is how do you share private key across multiple machines I work on?

**Comment by stefanbirkner** [comment]
They are just files that can be copied ;-)

**Pull request merged**
