### PR TITLE
Update hamcrest dependency

### LINKED ISSUE #28: Update hamcrest to 2.2
The version of the hamcrest dependency is outdated. The latest version is 2.2. The packaging of hamcrest has been changed with 2.x (http://hamcrest.org/JavaHamcrest/distributables#upgrading-from-hamcrest-1x). I will open a PR to fix this.

### PR DESCRIPTION
**Pull request by saarmbruster**
This PR fixes #28

### CODE REVIEW

**Comment by npathai** [comment]
@saarmbruster I will review this and get it merged soon.

**Comment by IncPlusPlus** [comment]
Is this still waiting on a review?

**Comment by npathai** [comment]
@IncPlusPlus Done. Sorry for the delay, was consumed with other priorities. I will release a new artifact tomorrow.
@saarmbruster Thank you so much for your contribution!

**Comment by IncPlusPlus** [comment]
No worries! I completely understand.

**Pull request merged**
